---
openapi: 3.0.1
info:
  title: NLIMS API
  version: v1
paths:
  "/api/v1/re_authenticate/{username}/{password}":
    get:
      summary: Login
      tags:
      - Users
      parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
      - name: password
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  error:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: re authentication successfuly
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        example: pgq13sZpUFT6
                      expiry_time:
                        type: string
                        example: '20231017180719'
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 401
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: wrong username or password
                  data:
                    type: object
                    example: {}
  "/api/v2/csig/generate_ids":
    post:
      summary: generate specimen tracking ids
      tags:
      - CSIG
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 221200
                    sequence_number:
                      type: string
                      example: '221200'
                    base9_equivalent:
                      type: string
                      example: '366377'
                    base9_zero_padded:
                      type: string
                      example: '0000366377'
                    encrypted:
                      type: string
                      example: '2155087835'
                    encrypted_zero_cleaned:
                      type: string
                      example: '3266198946'
                    check_digit:
                      type: string
                      example: '74'
                    sin:
                      type: string
                      example: '743266198946'
                    created_at:
                      type: string
                      format: date-time
                      example: '2023-10-17T14:57:18.000+02:00'
                    updated_at:
                      type: string
                      format: date-time
                      example: '2023-10-17T14:57:18.000+02:00'
                    distributed:
                      type: boolean
                      example: false
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                number_of_ids:
                  type: integer
                  example: 10
                  default: 100
              required:
              - number_of_ids
  "/api/v2/csig/distribute_ids":
    post:
      summary: distribute specimen tracking ids
      tags:
      - CSIG
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                site_name:
                  type: string
                number_of_ids:
                  type: integer
              required:
              - site_name
              - number_of_ids
  "/api/v2/csig/sin_used":
    get:
      summary: check if specimen tracking id is used
      tags:
      - CSIG
      parameters:
      - name: sin
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/api/v2/csig/use_sin":
    post:
      summary: use_sin csig
      tags:
      - CSIG
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sin:
                  type: string
                site_name:
                  type: string
                system_name:
                  type: string
              required:
              - sin
              - site_name
  "/api/v2/csig":
    get:
      summary: list csig specimen tracking ids
      tags:
      - CSIG
      parameters:
      - name: per_page
        in: query
        required: false
        schema:
          type: integer
      - name: page_number
        in: query
        required: false
        schema:
          type: integer
      - name: distributed
        in: query
        required: false
        schema:
          type: boolean
      - name: status
        in: query
        required: false
        schema:
          type: integer
      - name: q
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: successful
servers:
- url: http://localhost:3009
  variables:
    defaultHost:
      default: localhost:3009
components:
  securitySchemes:
    authorization:
      type: apiKey
      name: token
      in: header
security:
- authorization: []
