---
openapi: 3.0.1
info:
  title: NLIMS API
  version: v1
paths:
  "/api/v2/csig/generate_ids":
    post:
      summary: generate_specimen_tracking_id csig
      responses:
        '200':
          description: successful
  "/api/v2/csig/distribute_ids":
    post:
      summary: distribute_sin csig
      responses:
        '200':
          description: successful
  "/api/v2/csig/sin_used":
    get:
      summary: check_if_sin_is_used csig
      responses:
        '200':
          description: successful
  "/api/v2/csig/use_sin":
    post:
      summary: use_sin csig
      responses:
        '200':
          description: successful
  "/api/v2/csig":
    get:
      summary: list csigs
      responses:
        '200':
          description: successful
    post:
      summary: create csig
      responses:
        '200':
          description: successful
  "/api/v2/csig/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show csig
      responses:
        '200':
          description: successful
    patch:
      summary: update csig
      responses:
        '200':
          description: successful
    put:
      summary: update csig
      responses:
        '200':
          description: successful
    delete:
      summary: delete csig
      responses:
        '200':
          description: successful
servers:
- url: http://localhost:3009
  variables:
    defaultHost:
      default: localhost:3009
