development: &development
  protocol: 'http'
  host: 192.168.3.203
  port: 5984
  prefix: nlims
  suffix: repo
  username: root
  password: password
test:
  <<: *development
  suffix: test

production:
  <<: *development
  protocol: 'http'
