# frozen_string_literal: true

# MZ-HCM-26229-0417 — country, the facility that collected the sample, the year
# and day of the year, and that facility's sequence for the day.
#
# The number is always generated by the local node, and always by taking a
# locked counter: the current system reads `TrackingNumberTrail.last` and adds
# one, which hands the same number to two samples registered at the same moment.
# The unique index on `orders.tracking_number` is what makes that impossible
# rather than merely unlikely; this class is what stops it from being reached.
class TrackingNumber
  COUNTRY = "MZ"

  # Four digits is a day's worth for any facility in the country, but the format
  # does not break if one ever needs a fifth.
  FORMAT = /\A[A-Z]{2}-[A-Z0-9](?:[A-Z0-9-]*[A-Z0-9])?-\d{5}-\d{4,}\z/

  class << self
    def generate(facility_code:, at: Time.current)
      code = facility(facility_code)
      day = day_stamp(at)

      # Per facility and per day, so two facilities never queue behind each
      # other and the counter starts again each morning.
      number = Sequence.next!("tracking:#{code}:#{day}")

      format("%s-%s-%s-%04d", COUNTRY, code, day, number)
    end

    def matches?(value)
      FORMAT.match?(value.to_s)
    end

    private

    def facility(code)
      raise ArgumentError, "a tracking number needs the facility code that collected the sample" if code.blank?

      code.to_s.strip.upcase
    end

    # Two digits of year and three of day of year: sortable, and short enough
    # that the whole number stays readable over a telephone.
    def day_stamp(time)
      time.in_time_zone.strftime("%y%j")
    end
  end
end
